#!/usr/bin/env python3
"""Generate GNU gettext catalogs for monica-gtk.

msgid is a stable key (issue #7/#8 键集). zh_CN keeps Avalonia-concise Chinese;
en is short GNOME-style English. Source of truth for translators is the .po
files this writes; edit those (or this table) then re-run.
"""
from __future__ import annotations

from pathlib import Path

# key -> (zh_CN, en)
CATALOG: dict[str, tuple[str, str]] = {
    # App / nav
    "app.name": ("Monica", "Monica"),
    "nav.workspace": ("工作区", "Workspace"),
    "nav.passwords": ("密码库", "Password Vault"),
    "nav.generator": ("生成器", "Generator"),
    "nav.otp": ("动态口令", "Authenticator"),
    "nav.notes": ("安全笔记", "Secure Notes"),
    "nav.wallet": ("钱包", "Wallet"),
    "nav.timeline": ("时间线", "Timeline"),
    "nav.recycle": ("回收站", "Recycle Bin"),
    "nav.archive": ("归档", "Archive"),
    "nav.backup": ("备份同步", "Backup & Sync"),
    "nav.transfer": ("导入导出", "Import / Export"),
    "nav.workbench": ("工作台", "Workbench"),
    "nav.settings": ("设置", "Settings"),
    "nav.lock": ("锁定", "Lock"),
    "nav.lock_tooltip": ("锁定密码库", "Lock the password library"),
    "nav.settings_tooltip": ("设置", "Settings"),
    # Common
    "common.cancel": ("取消", "Cancel"),
    "common.ok": ("确定", "OK"),
    "common.save": ("保存", "Save"),
    "common.delete": ("删除", "Delete"),
    "common.edit": ("编辑", "Edit"),
    "common.copy": ("复制", "Copy"),
    "common.archive": ("归档", "Archive"),
    "common.new": ("新建", "New"),
    "common.detail": ("详情", "Details"),
    "common.select_item": ("请选择一条目", "Select an item"),
    "common.select_item_short": ("选择一条目", "Select an item"),
    "common.dash": ("—", "—"),
    "common.emdash": ("—", "—"),
    "common.all_files": ("所有文件", "All files"),
    "common.unlock_first": ("请先解锁", "Unlock first"),
    "common.unlock_page_hint": ("解锁后即可使用。", "Available after unlock."),
    "common.select_item_hint": ("点列表中的一条目查看详情。", "Select an item in the list."),
    "common.background_failed": ("后台任务失败", "Background task failed"),
    "common.failed": ("失败：{0}", "Failed: {0}"),
    "common.saving": ("正在保存…", "Saving…"),
    "common.deleting": ("正在删除…", "Deleting…"),
    "common.archiving": ("正在归档…", "Archiving…"),
    "common.reading": ("正在读取…", "Reading…"),
    "common.processing": ("正在处理…", "Working…"),
    "common.saved": ("已保存", "Saved"),
    "common.deleted": ("已删除", "Deleted"),
    "common.archived": ("已归档", "Archived"),
    "common.title": ("标题", "Title"),
    "common.notes": ("备注", "Notes"),
    "common.type": ("类型", "Type"),
    "common.time": ("时间", "Time"),
    "common.path": ("路径", "Path"),
    "common.need_title": ("请填写标题", "Title is required"),
    # Unlock / first-run gate
    "unlock.heading": ("解锁密码库", "Unlock"),
    "unlock.intro": ("输入主密码以打开本地密码库。", "Enter the master password to open the local password library."),
    "unlock.onboard_heading": ("还没有本地密码库", "No local password library yet"),
    "unlock.onboard_intro": (
        "选择保存路径并设置主密码，再输入一次确认。默认在用户数据目录。",
        "Choose a path, set a master password, and confirm it. The default is in the user data directory.",
    ),
    "unlock.path": ("密码库路径", "Path"),
    "unlock.browse": ("打开已有 .mdbx", "Open an existing .mdbx"),
    "unlock.save_as": ("选择新建路径", "Choose a new path"),
    "unlock.password": ("主密码", "Master password"),
    "unlock.confirm_password": ("确认主密码", "Confirm master password"),
    "unlock.group": ("本地密码库", "Local password library"),
    "unlock.button": ("解锁", "Unlock"),
    "unlock.create_enter": ("创建并进入", "Create and enter"),
    "unlock.create_new": ("新建密码库", "Create a new library"),
    "unlock.open_existing": ("打开已有密码库", "Open an existing library"),
    "unlock.inspect": ("仅打开（不解锁）", "Open only (no unlock)"),
    "unlock.idle": ("尚未打开密码库。", "No password library opened yet."),
    "unlock.choose_open": ("选择 Monica 密码库", "Choose a Monica password library"),
    "unlock.choose_create": ("新建 Monica 密码库", "Create a Monica password library"),
    "unlock.filter": ("Monica 密码库 (*.mdbx)", "Monica password library (*.mdbx)"),
    "unlock.need_password": ("请输入主密码", "Enter the master password"),
    "unlock.need_password_create": ("请输入主密码后再创建密码库", "Enter a master password before creating the library"),
    "unlock.need_confirm": ("请再次输入主密码", "Confirm the master password"),
    "unlock.password_mismatch": ("两次输入的主密码不一致", "The two passwords do not match"),
    "unlock.unlocking": ("正在解锁密码库…", "Unlocking…"),
    "unlock.creating": ("正在创建密码库…", "Creating password library…"),
    "unlock.inspecting": ("正在只读检查密码库…", "Inspecting (read-only)…"),
    "unlock.unlocked": ("已解锁", "Unlocked"),
    "unlock.created": ("已创建并解锁密码库", "Created and unlocked"),
    "unlock.locked_readonly": ("未解锁（只读）", "Locked (read-only)"),
    "unlock.inspect_ok": ("已打开（只读，未解锁）", "Opened (read-only, locked)"),
    "unlock.inspect_upgrade": (
        "\n升级：当前格式需要迁移。本次为只读打开，未改写文件。请先复制/备份再解锁。",
        "\nUpgrade: this format needs migration. Opened read-only; the file was not rewritten. Copy or back up before unlock.",
    ),
    "unlock.inspect_status": (
        "已打开（只读，未解锁）\n路径：{0}\nvault_id：{1}\n格式：{2}  schema：{3}  Tiga：{4}\n会话：{5}{6}",
        "Opened (read-only, locked)\nPath: {0}\nvault_id: {1}\nFormat: {2}  schema: {3}  Tiga: {4}\nSession: {5}{6}",
    ),
    "unlock.session_status": (
        "{0}\n路径：{1}\nvault_id：{2}\n格式：{3}  schema：{4}  Tiga：{5}\n会话：已解锁",
        "{0}\nPath: {1}\nvault_id: {2}\nFormat: {3}  schema: {4}  Tiga: {5}\nSession: unlocked",
    ),
    # Lock
    "lock.done": ("已锁定密码库", "Locked"),
    "lock.status": ("密码库已锁定。请输入主密码重新解锁。", "Locked. Enter the master password to unlock."),
    "lock.idle": ("空闲超时，已自动锁定", "Idle timeout; locked automatically"),
    "lock.discard_editors": ("已关闭未保存的编辑", "Unsaved editors closed"),
    # Passwords
    "passwords.list_title": ("密码", "Passwords"),
    "passwords.empty": ("还没有密码条目", "No password items yet"),
    "passwords.empty_add": ("点右上角 + 新建登录项。", "Tap + to add a login."),
    "passwords.locked_desc": ("解锁后这里会列出登录项。", "Logins appear here after unlock."),
    "passwords.new_tooltip": ("新建条目", "New item"),
    "passwords.show": ("显示", "Show"),
    "passwords.hide": ("隐藏", "Hide"),
    "passwords.copy_user": ("复制用户名", "Copy username"),
    "passwords.copy_password": ("复制密码", "Copy password"),
    "passwords.copy_otp": ("复制口令", "Copy code"),
    "passwords.username": ("用户名", "Username"),
    "passwords.url": ("网址", "Website"),
    "passwords.password": ("密码", "Password"),
    "passwords.otp": ("动态口令", "Authenticator"),
    "passwords.clipboard_hint": (
        "复制密码后 {0} 秒清除剪贴板（GdkClipboard / 门户）。空闲 {1} 秒自动锁定。",
        "Clipboard clears {0}s after copying a password (GdkClipboard / portal). Auto-lock after {1}s idle.",
    ),
    "passwords.detail_empty": (
        "密码默认隐藏。点「显示」才会把明文放进界面，离开或锁定时立即清掉。",
        "Passwords stay hidden. Show places plaintext in the UI; it is cleared on leave or lock.",
    ),
    "passwords.no_username": ("没有可复制的用户名", "No username to copy"),
    "passwords.copied_user": ("已复制用户名", "Username copied"),
    "passwords.reading_list": ("正在读取密码列表…", "Loading password list…"),
    "passwords.reading_item": ("正在读取条目…", "Loading item…"),
    "passwords.no_user": ("无用户名", "No username"),
    "passwords.otp_remaining": ("{0}  ·  {1} 秒", "{0}  ·  {1}s"),
    "passwords.delete_q": ("删除此条目？", "Delete this item?"),
    "passwords.delete_d": ("将移入回收站。", "It will move to the Recycle Bin."),
    "passwords.deleted": ("已删除条目", "Item deleted"),
    "passwords.new_title": ("新建条目", "New item"),
    "passwords.edit_title": ("编辑条目", "Edit item"),
    "passwords.otp_secret": ("动态口令密钥", "Authenticator secret"),
    "passwords.generate_tip": ("生成", "Generate"),
    "passwords.form": ("登录信息", "Login"),
    "passwords.filled": ("已填入", "Filled in"),
    "passwords.saved": ("已保存条目", "Item saved"),
    "folders.all": ("全部", "All"),
    "folders.new": ("新建文件夹", "New folder"),
    "folders.name": ("名称", "Name"),
    "folders.assign": ("文件夹", "Folder"),
    "folders.need_name": ("请填写名称", "Name is required"),
    "folders.created": ("已创建文件夹", "Folder created"),
    "folders.rename": ("重命名", "Rename"),
    "folders.renamed": ("已重命名", "Renamed"),
    "folders.move": ("移出条目", "Move items"),
    "folders.move_d": ("将此文件夹内的条目移到所选文件夹。", "Move this folder’s items to the selected folder."),
    "folders.moved": ("已移出 {0} 条", "Moved {0} items"),
    "folders.need_other": ("请先另建一个文件夹", "Create another folder first"),
    "folders.delete": ("删除文件夹", "Delete folder"),
    "folders.delete_q": ("删除此文件夹？", "Delete this folder?"),
    "folders.delete_d": ("仅空文件夹可删。请先移出条目。", "Only empty folders can be deleted. Move items out first."),
    "folders.deleted": ("已删除文件夹", "Folder deleted"),
    "folders.reading": ("正在读取文件夹…", "Loading folders…"),
    # Generator
    "generator.length": ("长度", "Length"),
    "generator.upper": ("大写", "Uppercase"),
    "generator.lower": ("小写", "Lowercase"),
    "generator.digits": ("数字", "Digits"),
    "generator.symbols": ("符号", "Symbols"),
    "generator.charset": ("字符", "Characters"),
    "generator.click": ("点「生成」", "Tap Generate"),
    "generator.generate": ("生成", "Generate"),
    "generator.result": ("结果", "Result"),
    "generator.hint": ("编辑登录项时可点「生成」填入密码。", "In a login editor, Generate fills the password."),
    "generator.need": ("请先生成", "Generate first"),
    "generator.strength": ("强度：{0}", "Strength: {0}"),
    "generator.strength.very_strong": ("极强", "Excellent"),
    "generator.strength.strong": ("强", "Strong"),
    "generator.strength.medium": ("中", "Fair"),
    "generator.strength.weak": ("弱", "Weak"),
    "generator.strength.very_weak": ("很弱", "Very weak"),
    # OTP
    "otp.empty": ("还没有动态口令", "No authenticators yet"),
    "otp.empty_add": ("点 + 添加，或在登录项里填写密钥。", "Tap + to add, or store a secret on a login."),
    "otp.issuer": ("签发", "Issuer"),
    "otp.account": ("账户", "Account"),
    "otp.code": ("口令", "Code"),
    "otp.standalone": ("独立", "Standalone"),
    "otp.login": ("登录项", "Login"),
    "otp.clear_login": ("清除此登录项的动态口令？", "Clear the authenticator on this login?"),
    "otp.delete_q": ("删除此动态口令？", "Delete this authenticator?"),
    "otp.delete_d": ("独立条目会移入回收站。", "Standalone items move to the Recycle Bin."),
    "otp.reading": ("正在读取动态口令…", "Loading authenticators…"),
    "otp.seconds": ("{0} 秒", "{0}s"),
    "otp.period": ("周期（秒）", "Period (seconds)"),
    "otp.digits": ("位数", "Digits"),
    "otp.secret": ("密钥", "Secret"),
    "otp.algorithm": ("算法", "Algorithm"),
    "otp.otp_type": ("口令类型", "OTP type"),
    "otp.sha1": ("SHA1", "SHA1"),
    "otp.sha256": ("SHA256", "SHA256"),
    "otp.sha512": ("SHA512", "SHA512"),
    "otp.type_totp": ("TOTP", "TOTP"),
    "otp.type_hotp": ("HOTP", "HOTP"),
    "otp.type_steam": ("Steam", "Steam"),
    "otp.counter": ("计数器", "Counter"),
    "otp.form_desc": ("支持 otpauth:// 或 Base32 密钥。", "Accepts otpauth:// or a Base32 secret."),
    "otp.new": ("新建动态口令", "New authenticator"),
    "otp.edit": ("编辑动态口令", "Edit authenticator"),
    # Notes
    "notes.empty": ("还没有笔记", "No notes yet"),
    "notes.empty_add": ("点右上角 + 新建笔记。", "Tap + to add a note."),
    "notes.tags": ("标签", "Tags"),
    "notes.content": ("内容", "Content"),
    "notes.preview": ("预览", "Preview"),
    "notes.delete_q": ("删除此笔记？", "Delete this note?"),
    "notes.delete_d": ("将移入回收站。", "It will move to the Recycle Bin."),
    "notes.reading": ("正在读取笔记…", "Loading notes…"),
    "notes.plain": ("纯文本", "Plain text"),
    "notes.markdown": ("Markdown", "Markdown"),
    "notes.form": ("笔记", "Note"),
    "notes.new": ("新建笔记", "New note"),
    "notes.edit": ("编辑笔记", "Edit note"),
    # Wallet
    "wallet.empty": ("还没有钱包条目", "No wallet items yet"),
    "wallet.empty_add": ("点 + 新建银行卡或证件。", "Tap + to add a card or document."),
    "wallet.copy_number": ("复制号码", "Copy number"),
    "wallet.copy_cvv": ("复制 CVV", "Copy CVV"),
    "wallet.holder": ("持有人", "Holder"),
    "wallet.number": ("号码", "Number"),
    "wallet.bank": ("银行", "Bank"),
    "wallet.issuer": ("签发", "Issuer"),
    "wallet.extra": ("银行 / 签发", "Bank / issuer"),
    "wallet.expiry": ("有效期", "Expiry"),
    "wallet.cvv": ("CVV", "CVV"),
    "wallet.card": ("银行卡", "Bank card"),
    "wallet.document": ("证件", "Document"),
    "wallet.card_type": ("卡类型", "Card type"),
    "wallet.debit": ("借记卡", "Debit"),
    "wallet.credit": ("信用卡", "Credit"),
    "wallet.prepaid": ("预付卡", "Prepaid"),
    "wallet.card_name": ("卡名", "Card name"),
    "wallet.month": ("月", "Month"),
    "wallet.year": ("年", "Year"),
    "wallet.doc_type": ("证件类型", "Document type"),
    "wallet.doc_id": ("身份证", "ID card"),
    "wallet.doc_passport": ("护照", "Passport"),
    "wallet.doc_license": ("驾驶证", "Driver license"),
    "wallet.doc_ssn": ("社保号", "SSN"),
    "wallet.doc_other": ("其他", "Other"),
    "wallet.issued": ("签发日", "Issued"),
    "wallet.nationality": ("国籍", "Nationality"),
    "wallet.ph_card_name": ("例如: 工资卡", "e.g. Payroll card"),
    "wallet.ph_bank": ("例如: 中国工商银行", "e.g. ICBC"),
    "wallet.ph_number": ("1234 5678 9012 3456", "1234 5678 9012 3456"),
    "wallet.ph_holder": ("ZHANG SAN", "ZHANG SAN"),
    "wallet.ph_month": ("12", "12"),
    "wallet.ph_year": ("2025", "2025"),
    "wallet.ph_cvv": ("123", "123"),
    "wallet.ph_doc_title": ("例如: 我的身份证", "e.g. My ID card"),
    "wallet.ph_doc_id": ("110101199001011234", "110101199001011234"),
    "wallet.ph_doc_passport": ("E12345678", "E12345678"),
    "wallet.ph_doc_license": ("123456789012", "123456789012"),
    "wallet.ph_doc_ssn": ("1234567890", "1234567890"),
    "wallet.ph_doc_other": ("证件号码", "Document number"),
    "wallet.ph_doc_name": ("张三", "ZHANG SAN"),
    "wallet.ph_issued": ("2020/01/01", "2020/01/01"),
    "wallet.ph_expiry": ("2030/01/01", "2030/01/01"),
    "wallet.ph_issuer": ("例如: XX市公安局", "e.g. City Public Security Bureau"),
    "wallet.ph_nationality": ("例如：中国", "e.g. China"),
    "wallet.ph_notes": ("备注", "Notes"),
    "wallet.delete_q": ("删除此条目？", "Delete this item?"),
    "wallet.delete_d": ("将移入回收站。", "It will move to the Recycle Bin."),
    "wallet.reading": ("正在读取钱包…", "Loading wallet…"),
    "wallet.new": ("新建钱包条目", "New wallet item"),
    "wallet.edit": ("编辑钱包条目", "Edit wallet item"),
    # Timeline
    "timeline.empty": ("暂无记录", "No history yet"),
    "timeline.empty_desc": ("解锁后显示最近的密码库提交。", "Recent vault commits appear after unlock."),
    "timeline.pick": ("选择一条记录", "Select a record"),
    "timeline.locked_desc": ("时间线来自 MDBX 提交历史。", "Timeline is MDBX commit history."),
    "timeline.none": ("还没有提交历史。", "No commits yet."),
    "timeline.reading": ("正在读取时间线…", "Loading timeline…"),
    # Recycle / archive
    "recycle.empty": ("回收站是空的", "Recycle Bin is empty"),
    "recycle.empty_desc": ("软删除的条目会出现在这里。", "Soft-deleted items appear here."),
    "recycle.restore": ("恢复", "Restore"),
    "recycle.purge": ("永久删除", "Delete permanently"),
    "recycle.purge_q": ("永久删除此条目？", "Delete this item permanently?"),
    "recycle.purge_d": ("不可恢复。", "This cannot be undone."),
    "recycle.purged": ("已永久删除", "Permanently deleted"),
    "recycle.restored": ("已恢复", "Restored"),
    "recycle.reading": ("正在读取回收站…", "Loading Recycle Bin…"),
    "archive.empty": ("没有已归档条目", "Nothing archived"),
    "archive.empty_desc": ("归档写在条目载荷里，不另开存储。", "Archive is a flag on the item payload, not a separate store."),
    "archive.unarchive": ("取消归档", "Unarchive"),
    "archive.unarchived": ("已取消归档", "Unarchived"),
    "archive.reading": ("正在读取归档…", "Loading archive…"),
    # Backup / sync
    "backup.to_file": ("备份到文件", "Back up to file"),
    "backup.export_bundle": ("导出同步包", "Export sync bundle"),
    "backup.apply_bundle": ("应用同步包", "Apply sync bundle"),
    "backup.idle": ("尚未备份或同步。", "No backup or sync yet."),
    "backup.group": ("备份", "Backup"),
    "backup.group_desc": (
        "便携 .mdbx 副本：SQLite 在线备份，DELETE 日志，不含 WAL。密文，不解锁，不升级格式。目标文件必须不存在。",
        "Portable .mdbx copy: SQLite online backup, DELETE journal, no WAL. Ciphertext only; no unlock, no format upgrade. Target must not exist.",
    ),
    "backup.sync_group": ("离线同步包", "Offline sync bundle"),
    "backup.sync_group_desc": (
        "上游 mdbx-sync 完整包（魔数 MDBXSYNC，v3，SHA-256）。只能应用到同一 vault_id。",
        "Upstream mdbx-sync complete bundle (magic MDBXSYNC, v3, SHA-256). Apply only to the same vault_id.",
    ),
    "backup.save": ("保存便携备份", "Save portable backup"),
    "backup.filter": ("Monica 备份 (*.mdbx)", "Monica backup (*.mdbx)"),
    "backup.export_title": ("导出 MDBXSYNC 包", "Export MDBXSYNC bundle"),
    "backup.bundle_filter": ("同步包 (*.mdbx-sync)", "Sync bundle (*.mdbx-sync)"),
    "backup.exporting": ("正在导出同步包…", "Exporting sync bundle…"),
    "backup.exported": ("已导出同步包", "Sync bundle exported"),
    "backup.exported_status": (
        "已导出同步包\n路径：{0}\nvault_id：{1}\n提交：{2}  时间：{3}",
        "Sync bundle exported\nPath: {0}\nvault_id: {1}\nCommits: {2}  Time: {3}",
    ),
    "backup.apply_title": ("选择 MDBXSYNC 包", "Choose an MDBXSYNC bundle"),
    "backup.applying": ("正在应用同步包…", "Applying sync bundle…"),
    "backup.applied": ("已应用同步包", "Sync bundle applied"),
    "backup.applied_status": (
        "已应用同步包\n路径：{0}\nvault_id：{1}\n写入 {2} · 跳过 {3} · 冲突 {4} · 缺父 {5}",
        "Sync bundle applied\nPath: {0}\nvault_id: {1}\nApplied {2} · skipped {3} · conflicts {4} · missing parents {5}",
    ),
    "backup.backing_up": ("正在备份密码库…", "Backing up…"),
    "backup.done": ("已备份", "Backed up"),
    "backup.done_status": (
        "已备份\n路径：{0}\nvault_id：{1}\n格式：{2}  schema：{3}  大小：{4} 字节",
        "Backed up\nPath: {0}\nvault_id: {1}\nFormat: {2}  schema: {3}  Size: {4} bytes",
    ),
    "backup.done_locked_status": (
        "已备份（未解锁）\n路径：{0}\nvault_id：{1}\n格式：{2}  schema：{3}  大小：{4} 字节",
        "Backed up (locked)\nPath: {0}\nvault_id: {1}\nFormat: {2}  schema: {3}  Size: {4} bytes",
    ),
    "backup.notify": ("已完成密码库备份", "Backup finished"),
    "backup.sync_status_note": (
        "可用：把完整 MDBXSYNC 包拷到另一台已解锁的同一密码库。不可用：WebDAV / OneDrive / Bitwarden 在线同步、实时对端、增量包（需 checkpoint）。",
        "Available: copy a complete MDBXSYNC bundle onto another unlocked copy of the same vault. Not available: WebDAV / OneDrive / Bitwarden online sync, live peers, or incremental bundles (need a checkpoint).",
    ),
    "backup.online_blocked_title": ("在线同步", "Online sync"),
    "backup.online_blocked": (
        "未接 WebDAV / OneDrive / Bitwarden。上游 mdbx-sync 是传输无关的包与 SyncClient 线协议，没有现成的门户凭据通路。请用离线完整包。",
        "WebDAV / OneDrive / Bitwarden are not wired. Upstream mdbx-sync is transport-neutral bundles plus a SyncClient wire protocol, with no portal-credentials path. Use a complete offline bundle.",
    ),
    # Transfer
    "transfer.export_monica": ("导出 Monica JSON", "Export Monica JSON"),
    "transfer.kdbx_bin": ("二进制 KDBX", "Binary KDBX"),
    "transfer.import_monica": ("导入 Monica JSON", "Import Monica JSON"),
    "transfer.export_kdbx": ("导出 KDBX JSON", "Export KDBX JSON"),
    "transfer.import_kdbx": ("导入 KDBX JSON", "Import KDBX JSON"),
    "transfer.export_kdbx_bin": ("导出二进制 KDBX", "Export binary KDBX"),
    "transfer.import_kdbx_bin": ("导入二进制 KDBX", "Import binary KDBX"),
    "transfer.export_password_csv": ("导出密码 CSV", "Export password CSV"),
    "transfer.export_combined_csv": ("导出全部 CSV", "Export all CSV"),
    "transfer.import_csv": ("导入 CSV", "Import CSV"),
    "transfer.idle": ("尚未导入或导出。", "Nothing imported or exported yet."),
    "transfer.monica_desc": (
        "格式 `{0}`：登录 / 笔记 / 钱包 / 独立口令。明文密钥，请妥善保管。",
        "Format `{0}`: logins / notes / wallet / standalone authenticators. Plaintext secrets — keep the file safe.",
    ),
    "transfer.kdbx_desc": (
        "与 mdbx-cli 的 import-kdbx-json / 逻辑条目 JSON 相同。导入按上游规则为每条建 project。GTK 多登录共用一个默认 project，故导出按登录条目写出，而不是按 project 折叠。",
        "Same as mdbx-cli import-kdbx-json / logical entry JSON. Import creates a project per entry. GTK keeps several logins in one default project, so export writes logins instead of folding a project.",
    ),
    "transfer.kdbx_bin_desc": (
        "KeePass KDBX4（上游 keepass crate）。导入 / 导出需要单独的文件密码（SecretString），I/O 在后台线程。只覆盖登录条目。",
        "KeePass KDBX4 (upstream keepass crate). Import / export need a separate file password (SecretString). I/O is off the UI thread. Logins only.",
    ),
    "transfer.csv_desc": (
        "密码 CSV 表头与 Avalonia 对齐（title,website,username,password,notes,authenticatorKey,…）。「全部 CSV」含 kind 列，覆盖登录 / 笔记 / 钱包 / 口令。导入按表头自动识别。",
        "Password CSV headers match Avalonia (title,website,username,password,notes,authenticatorKey,…). All-CSV has a kind column for logins / notes / wallet / authenticators. Import detects the header.",
    ),
    "transfer.note": (
        "未做：Bitwarden JSON。Avalonia 钱包 CSV 的编码 Data 会跳过。在线同步不在本页。",
        "Not done: Bitwarden JSON. Encoded Avalonia wallet CSV Data is skipped. Online sync is not on this page.",
    ),
    "transfer.json_filter": ("JSON (*.json)", "JSON (*.json)"),
    "transfer.csv_filter": ("CSV (*.csv)", "CSV (*.csv)"),
    "transfer.kdbx_filter": ("KDBX (*.kdbx)", "KDBX (*.kdbx)"),
    "transfer.file_password": ("KDBX 文件密码", "KDBX file password"),
    "transfer.file_password_export": ("设置该 .kdbx 的文件密码。与密码库主密码无关。", "Set the .kdbx file password. It is not the master password."),
    "transfer.file_password_import": ("输入该 .kdbx 的文件密码。", "Enter the .kdbx file password."),
    "transfer.exported_monica": ("已导出 Monica JSON", "Monica JSON exported"),
    "transfer.imported_monica": ("已导入 Monica JSON", "Monica JSON imported"),
    "transfer.exported_kdbx": ("已导出 KDBX JSON", "KDBX JSON exported"),
    "transfer.imported_kdbx": ("已导入 KDBX JSON", "KDBX JSON imported"),
    "transfer.exported_kdbx_bin": ("已导出二进制 KDBX", "Binary KDBX exported"),
    "transfer.imported_kdbx_bin": ("已导入二进制 KDBX", "Binary KDBX imported"),
    "transfer.exported_password_csv": ("已导出密码 CSV", "Password CSV exported"),
    "transfer.exported_combined_csv": ("已导出全部 CSV", "All CSV exported"),
    "transfer.imported_csv": ("已导入 CSV", "CSV imported"),
    "transfer.exporting": ("正在导出…", "Exporting…"),
    "transfer.importing": ("正在导入…", "Importing…"),
    "transfer.summary": ("{0}\n路径：{1}\n{2}", "{0}\nPath: {1}\n{2}"),
    # Workbench
    "workbench.refresh": ("刷新", "Refresh"),
    "workbench.hint": ("不会在此就地把 MDBX-1 升级为 MDBX-2。需要升级时请先备份。", "This page never upgrades MDBX-1 to MDBX-2 in place. Back up first if an upgrade is required."),
    "workbench.idle": ("尚未检查。", "Not checked yet."),
    "workbench.vault_id": ("vault_id", "vault_id"),
    "workbench.format": ("格式", "Format"),
    "workbench.schema": ("schema", "schema"),
    "workbench.tiga": ("Tiga", "Tiga"),
    "workbench.session": ("会话", "Session"),
    "workbench.migration": ("迁移", "Migration"),
    "workbench.counts": ("计数", "Counts"),
    "workbench.size": ("大小", "Size"),
    "workbench.reading": ("正在读取工作台…", "Loading workbench…"),
    "workbench.inspecting": ("正在只读检查…", "Inspecting (read-only)…"),
    "workbench.schema_target": ("{0} → 目标 {1}", "{0} → target {1}"),
    "workbench.unlocked": ("已解锁", "Unlocked"),
    "workbench.locked": ("未解锁（只读）", "Locked (read-only)"),
    "workbench.upgrade_yes": ("需要", "Required"),
    "workbench.upgrade_no": ("否", "No"),
    "workbench.ext_yes": ("有", "Yes"),
    "workbench.ext_no": ("无", "No"),
    "workbench.migration_line": (
        "升级：{0}  读：{1}  写：{2}  未知扩展：{3}",
        "Upgrade: {0}  read: {1}  write: {2}  unknown extensions: {3}",
    ),
    "workbench.counts_line": (
        "登录 {0} · 笔记 {1} · 卡 {2} · 口令 {3} · 证件 {4} · 其他 {5} · 回收站 {6} · 项目 {7} · 提交 {8}",
        "Logins {0} · notes {1} · cards {2} · authenticators {3} · documents {4} · other {5} · recycle {6} · projects {7} · commits {8}",
    ),
    "workbench.bytes": ("{0} 字节", "{0} bytes"),
    "workbench.ok_hint": ("当前格式可解锁。不会在此就地升级 MDBX-1。", "This format can unlock. MDBX-1 is never upgraded here in place."),
    "workbench.refreshed": ("已刷新。", "Refreshed."),
    # Settings
    "settings.autolock": ("自动锁定", "Auto-lock"),
    "settings.autolock_sub": ("空闲分钟后锁定", "Lock after idle minutes"),
    "settings.clipboard": ("剪贴板清除", "Clipboard clear"),
    "settings.clipboard_sub": ("复制后秒数", "Seconds after copy"),
    "settings.security": ("安全", "Security"),
    "settings.security_desc": (
        "短超时，写在本机配置文件。环境变量若已设置会在下次启动覆盖。",
        "Short timeouts, stored in the local config file. Environment variables override on the next start if set.",
    ),
    "settings.notify": ("桌面通知", "Desktop notifications"),
    "settings.notify_sub": ("剪贴板清除、自动锁定、备份完成", "Clipboard clear, auto-lock, backup done"),
    "settings.tray": ("关闭时留在托盘", "Close to tray"),
    "settings.tray_sub": ("无托盘时关闭即退出", "Without a tray, close quits"),
    "settings.desktop": ("桌面", "Desktop"),
    "settings.desktop_desc": (
        "通知走 Gio Notification（Wayland 上为 portal）。托盘为 StatusNotifierItem。",
        "Notifications use Gio Notification (portal on Wayland). Tray is StatusNotifierItem.",
    ),
    "settings.file_chooser": ("文件选择", "File chooser"),
    "settings.notifications": ("通知", "Notifications"),
    "settings.shortcuts": ("全局快捷键", "Global shortcuts"),
    "settings.tray_cap": ("托盘", "Tray"),
    "settings.caps": ("运行时能力", "Runtime capabilities"),
    "settings.caps_desc": (
        "启动时探测 D-Bus / portal，不硬编码「平台受限」。",
        "Probed on D-Bus / portals at start; never hardcoded as platform-limited.",
    ),
    "settings.bind": ("注册全局快捷键", "Bind global shortcut"),
    "settings.bind_tip": ("首选 {0} 显示/隐藏。需系统对话框确认。", "Preferred trigger {0} show/hide. The system dialog must confirm."),
    "settings.reprobe": ("重新探测", "Probe again"),
    "settings.config": ("配置：{0}", "Config: {0}"),
    "settings.env_autolock": ("已设 MONICA_GTK_AUTO_LOCK_SECS", "MONICA_GTK_AUTO_LOCK_SECS is set"),
    "settings.env_clipboard": ("已设 MONICA_GTK_CLIPBOARD_CLEAR_SECS", "MONICA_GTK_CLIPBOARD_CLEAR_SECS is set"),
    "settings.env_none": ("未设环境变量覆盖。窗口内 Ctrl+L 锁定，Ctrl+Q 退出。", "No environment overrides. Ctrl+L locks, Ctrl+Q quits."),
    "settings.waiting_bind": ("等待系统对话框确认快捷键…", "Waiting for the system dialog to confirm the shortcut…"),
    "settings.reprobed": ("已重新探测桌面能力", "Desktop capabilities probed again"),
    "settings.probing": ("探测中…", "Probing…"),
    "settings.probe_failed": ("探测任务失败", "Probe task failed"),
    "settings.language": ("语言", "Language"),
    "settings.language_sub": ("切换后立即写入；已打开的控件下次启动更新。", "Saved immediately. Open widgets update on next start."),
    "settings.language_system": ("系统", "System"),
    "settings.language_zh": ("简体中文", "Chinese"),
    "settings.language_en": ("English", "English"),
    "settings.language_saved": ("已保存语言。部分文案下次启动更新。", "Language saved. Some copy updates on next start."),
    "settings.vault": ("密码库", "Password library"),
    "settings.vault_path": ("当前路径", "Current path"),
    "settings.vault_open": ("打开另一个", "Open another"),
    "settings.vault_create": ("新建", "Create new"),
    "settings.vault_desc": ("打开另一个或新建会先锁定当前会话。", "Opening another or creating new locks the current session first."),
    # Desktop / tray / shortcuts
    "desktop.gnome_tray_hint": (
        "GNOME 需 AppIndicator 扩展（gnome-shell-extension-appindicator）",
        "GNOME needs the AppIndicator extension (gnome-shell-extension-appindicator)",
    ),
    "desktop.file_portal": ("GtkFileDialog · FileChooser portal 已探测", "GtkFileDialog · FileChooser portal probed"),
    "desktop.file_fallback": ("GtkFileDialog · 无 FileChooser portal，GTK 后端回退", "GtkFileDialog · no FileChooser portal; GTK backend fallback"),
    "desktop.file_no_bus": ("GtkFileDialog · 无会话总线（{0}）", "GtkFileDialog · no session bus ({0})"),
    "desktop.notify_portal": ("Gio Notification · Notification portal 已探测", "Gio Notification · Notification portal probed"),
    "desktop.notify_fdo": ("Gio Notification · 仅有 org.freedesktop.Notifications", "Gio Notification · org.freedesktop.Notifications only"),
    "desktop.notify_toast": ("会话无通知服务，仅应用内 toast", "No session notification service; in-app toast only"),
    "desktop.notify_no_bus": ("无会话总线（{0}）", "No session bus ({0})"),
    "desktop.shortcut_unbound": ("portal 已探测，尚未绑定", "Portal probed, not bound yet"),
    "desktop.shortcut_missing": ("portal 无 GlobalShortcuts（会话/后端未提供）", "Portal has no GlobalShortcuts (session/backend missing)"),
    "desktop.shortcut_no_portal": ("无 xdg-desktop-portal", "No xdg-desktop-portal"),
    "desktop.shortcut_no_bus": ("无会话总线（{0}）", "No session bus ({0})"),
    "desktop.tray_ok": ("StatusNotifierWatcher 已探测", "StatusNotifierWatcher probed"),
    "desktop.tray_missing": ("未发现托盘 watcher。{0}", "No tray watcher. {0}"),
    "desktop.tray_no_bus": ("无会话总线（{0}）", "No session bus ({0})"),
    "desktop.unknown": ("未知", "unknown"),
    "desktop.not_probed": ("尚未探测", "Not probed yet"),
    "desktop.bound": ("已绑定：{0}", "Bound: {0}"),
    "desktop.bound_trigger": ("已绑定：{0}（{1}）", "Bound: {0} ({1})"),
    "desktop.tray_connected": ("已连接 StatusNotifierItem", "StatusNotifierItem connected"),
    "desktop.tray_failed": ("托盘启动失败：{0}", "Tray failed to start: {0}"),
    "desktop.tray_offline": ("托盘 watcher 离线。{0}", "Tray watcher offline. {0}"),
    "desktop.toggle_id": ("显示/隐藏", "Show/hide"),
    "desktop.toggle_desc": ("显示或隐藏 Monica", "Show or hide Monica"),
    "shortcut.runtime_failed": ("快捷键运行时失败：{0}", "Shortcut runtime failed: {0}"),
    "shortcut.connect_failed": ("无法连接 GlobalShortcuts：{0}", "Cannot connect GlobalShortcuts: {0}"),
    "shortcut.session_failed": ("CreateSession 失败：{0}", "CreateSession failed: {0}"),
    "shortcut.list_failed": ("读取已绑定快捷键失败：{0}", "Failed to list bound shortcuts: {0}"),
    "shortcut.list_err": ("ListShortcuts 失败：{0}", "ListShortcuts failed: {0}"),
    "shortcut.list_timeout": ("ListShortcuts 超时（portal 无响应）", "ListShortcuts timed out (portal did not respond)"),
    "shortcut.listen_failed": ("无法监听快捷键：{0}", "Cannot listen for shortcuts: {0}"),
    "shortcut.rejected": ("绑定被拒绝或失败：{0}", "Bind rejected or failed: {0}"),
    "shortcut.bind_failed": ("绑定失败：{0}", "Bind failed: {0}"),
    "shortcut.bind_timeout": ("绑定超时（请在系统对话框中确认）", "Bind timed out (confirm in the system dialog)"),
    "shortcut.other_bound": ("已绑定 {0} 个快捷键（不含显示/隐藏）", "Bound {0} shortcuts (not show/hide)"),
    "tray.show": ("显示", "Show"),
    "tray.hide": ("隐藏", "Hide"),
    "tray.lock": ("锁定", "Lock"),
    "tray.quit": ("退出", "Quit"),
    "tray.unlocked": ("已解锁 · 点击显示或隐藏", "Unlocked · click to show or hide"),
    "tray.locked": ("已锁定 · 点击显示或隐藏", "Locked · click to show or hide"),
    # Dialogs / security
    "dialog.file_password": ("文件密码", "File password"),
    "dialog.file_password_empty": ("文件密码不能为空", "File password cannot be empty"),
    "security.copy_empty": ("没有可复制的内容", "Nothing to copy"),
    "security.copied": ("已复制，{0} 秒后清除剪贴板（若仍是本内容）", "Copied. Clipboard clears in {0}s if it is still this secret."),
    "security.cleared": ("已从剪贴板清除复制的秘密", "Copied secret cleared from the clipboard"),
}


def _po_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_po(path: Path, language: str, index: int) -> None:
    lines = [
        "# Monica GTK4 UI catalog. msgid is a stable key (键集).",
        "# SPDX-License-Identifier: GPL-3.0-or-later",
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: monica-gtk 0.1.0\\n"',
        f'"Language: {language}\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        "",
    ]
    for key in sorted(CATALOG):
        value = CATALOG[key][index]
        lines.append(f'msgid "{_po_escape(key)}"')
        lines.append(f'msgstr "{_po_escape(value)}"')
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_pot(path: Path) -> None:
    lines = [
        "# Monica GTK4 UI template. msgid is a stable key.",
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: monica-gtk 0.1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        "",
    ]
    for key in sorted(CATALOG):
        lines.append(f'msgid "{_po_escape(key)}"')
        lines.append('msgstr ""')
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    root = Path(__file__).resolve().parent
    write_po(root / "zh_CN.po", "zh_CN", 0)
    write_po(root / "en.po", "en", 1)
    write_pot(root / "monica-gtk.pot")
    (root / "LINGUAS").write_text("zh_CN\nen\n", encoding="utf-8")
    print(f"wrote {len(CATALOG)} keys → {root}")


if __name__ == "__main__":
    main()
